services:
  - type: web
    name: discord-ad-search-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: N8N_WEBHOOK_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
